export const FETCH_NOTES_REQUEST = 'FETCH_NOTES_REQUEST'
export const FETCH_NOTES_FAILED = 'FETCH_NOTES_FAILED'
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'

export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_FAILED = 'CREATE_NOTE_FAILED'

export const TRASH_NOTE_REQUEST = 'TRASH_NOTE_REQUEST'
export const TRASH_NOTE_SUCCESS = 'TRASH_NOTE_SUCCESS'
export const TRASH_NOTE_FAILED = 'TRASH_NOTE_FAILED'

export const RESTORE_NOTE_REQUEST = 'RESTORE_NOTE_REQUEST'
export const RESTORE_NOTE_SUCCESS = 'RESTORE_NOTE_SUCCESS'
export const RESTORE_NOTE_FAILED = 'RESTORE_NOTE_FAILED'

export const UPDATE_NOTE_REQUEST = 'UPDATE_NOTE_REQUEST'
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS'
export const UPDATE_NOTE_FAILED = 'UPDATE_NOTE_FAILED'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS'
export const DELETE_NOTE_FAILED = 'DELETE_NOTE_FAILED'